"""empty message

Revision ID: 48b82719cf94
Revises: 2018acf2d841
Create Date: 2024-07-27 19:32:02.329892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48b82719cf94'
down_revision: Union[str, None] = '2018acf2d841'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('pv', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'united_orders', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'united_orders', type_='unique')
    op.drop_column('products', 'pv')
    # ### end Alembic commands ###
