"""add field given_by

Revision ID: 4b6fd10ddcc5
Revises: b1e63e781920
Create Date: 2024-05-22 19:19:59.964715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b6fd10ddcc5'
down_revision: Union[str, None] = 'b1e63e781920'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('given_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'users', ['given_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'given_by')
    # ### end Alembic commands ###
