"""change user_id field type in ConfirmToken

Revision ID: 8b433d8eae8e
Revises: e498c19ae388
Create Date: 2024-05-05 20:45:03.623241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b433d8eae8e'
down_revision: Union[str, None] = 'e498c19ae388'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
