"""empty message

Revision ID: ae4a0a5c2f4d
Revises: f9a889dde083
Create Date: 2024-08-27 22:09:44.082689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae4a0a5c2f4d'
down_revision: Union[str, None] = 'f9a889dde083'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('price_rub', sa.Integer(), server_default='0', nullable=False))
    op.drop_column('products', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('products', 'price_rub')
    # ### end Alembic commands ###
