"""empty message

Revision ID: d0cfdc96d151
Revises: ae4a0a5c2f4d
Create Date: 2024-08-27 22:19:30.564271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0cfdc96d151'
down_revision: Union[str, None] = 'ae4a0a5c2f4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('price_byn', sa.Integer(), server_default='0', nullable=False))
    op.add_column('products', sa.Column('price_kzt', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'price_kzt')
    op.drop_column('products', 'price_byn')
    # ### end Alembic commands ###
