"""add is_verify field to User

Revision ID: d59cd8ecb2ec
Revises: 8b433d8eae8e
Create Date: 2024-05-05 21:15:57.823386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd59cd8ecb2ec'
down_revision: Union[str, None] = '8b433d8eae8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_verify', sa.Boolean(), server_default=sa.text('(false)'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_verify')
    # ### end Alembic commands ###
