"""empty message

Revision ID: dc7c2fe570a4
Revises: 48b82719cf94
Create Date: 2024-07-29 02:03:39.159303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc7c2fe570a4'
down_revision: Union[str, None] = '48b82719cf94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('united_orders', sa.Column('created_at', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('united_orders', 'created_at')
    # ### end Alembic commands ###
